---
kind: "operation"
client: "rug-cli 0.30.1"
generator:
  name: "NewStarterRugProject"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.25.0"
  origin:
    repo: "git@github.com:atomist-rugs/rug-editors.git"
    branch: "master"
    sha: "7557a1b"

---
kind: "operation"
client: "rug-cli 0.30.1"
editor:
  name: "AddTypeScriptEventHandler"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.25.0"
  origin:
    repo: "git@github.com:atomist-rugs/rug-editors.git"
    branch: "master"
    sha: "7557a1b"
  parameters:
    - "handlerName": "HandleSuccessfulBuild"
    - "description": "respond to successful build events"
    - "pathExpression": "/Build()"

