site_name: The Atomist Documentation
site_description: Documentation for the Atomist Developer Platform
site_author: The Atomist Team
copyright: '&copy; 2017 Atomist, Inc.'
extra:
  main_site_url: 'https://www.atomist.com/'
theme: material
#theme_dir: atomist
site_favicon: images/favicon.ico
extra:
  logo: 'images/atomist-logo-horiz-reversed.svg'
  palette:
    primary: 'green'
    accent: 'green'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/atomist'
    - type: 'twitter'
      link: 'https://twitter.com/atomist'
    - type: 'slack'
      link: 'https://join.atomist.com/'
extra_css:
  - 'stylesheets/extra.css'
google_analytics:
  - 'UA-74966852-1'
  - 'auto'
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false, linenums=true)
  - footnotes
  - meta
  - toc(permalink=true)
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
repo_name: 'Rug'
repo_url: 'https://github.com/atomist/rug'
pages:
- Welcome to Atomist: 'index.md'
- Getting Started:
  - Introduction: 'getting-started/index.md'
  - Before You Get Started: 'getting-started/before-you-get-started.md'
  - Invite Atomist to Slack: 'getting-started/invite-atomist-to-slack.md'
  - Connect Atomist to GitHub: 'getting-started/connect-atomist-to-github.md'
  - Putting Atomist to Work on Your Projects: 'getting-started/putting-atomist-to-work.md'
  - Connect Atomist to CI: 'getting-started/connect-atomist-to-ci.md'
  - Build Your Own Development Automation: 'getting-started/build-your-own-development-automation.md'
- Rug:
  - Introduction: 'rug/index.md'
  - CLI:
    - Introduction: 'rug/cli/index.md'
    - Installation: 'rug/cli/rug-cli-install.md'
    - Command Reference: 'rug/cli/rug-cli-commands.md'
  - Guides:
    - Introduction: 'rug/guides/index.md'
    - Rug Tests: 'rug/guides/rug-tests.md'
    - Rug Generators: 'rug/guides/rug-generators.md'
    - Rug Editors: 'rug/guides/rug-editors.md'
    - Rug Templates: 'rug/guides/rug-templates.md'
  - References:
    - Introduction: 'rug/reference/index.md'
    - Rug Conventions: 'rug/reference/rug-conventions.md'
    - Rug Project Structure: 'rug/reference/rug-project.md'
    - Rug Project Lifecycle: 'rug/reference/rug-lifecycle.md'
    - Rug Path Expressions: 'rug/reference/rug-path-expressions.md'
    - Rug Microgrammars: 'rug/reference/rug-microgrammars.md'
    - Rug Language Extensions:
      - Introduction: 'rug/reference/extensions/index.md'
      - CljProject: 'rug/reference/extensions/rug-extension-clj-project.md'
      - CSharpFile: 'rug/reference/extensions/rug-extension-c-sharp-file.md'
      - DockerFile: 'rug/reference/extensions/rug-extension-docker-file.md'
      - ElmModule: 'rug/reference/extensions/rug-extension-elm-module.md'
      - EveryPom: 'rug/reference/extensions/rug-extension-every-pom.md'
      - File: 'rug/reference/extensions/rug-extension-file.md'
      - JavaProject: 'rug/reference/extensions/rug-extension-java-project.md'
      - JavaSource: 'rug/reference/extensions/rug-extension-java-source.md'
      - JavaType: 'rug/reference/extensions/rug-extension-java-type.md'
      - Json: 'rug/reference/extensions/rug-extension-json.md'
      - Line: 'rug/reference/extensions/rug-extension-line.md'
      - Pom: 'rug/reference/extensions/rug-extension-pom.md'
      - Project: 'rug/reference/extensions/rug-extension-project.md'
      - Properties: 'rug/reference/extensions/rug-extension-properties.md'
      - PythonFile: 'rug/reference/extensions/rug-extension-python-file.md'
      - PythonRequirementsTxt: 'rug/reference/extensions/rug-extension-python-requirements-txt.md'
      - RugArchiveProject: 'rug/reference/extensions/rug-extension-rug-archive-project.md'
      - RugFile: 'rug/reference/extensions/rug-extension-rug-file.md'
      - ScalaFile: 'rug/reference/extensions/rug-extension-scala-file.md'
      - Services: 'rug/reference/extensions/rug-extension-services.md'
      - SpringBootProject: 'rug/reference/extensions/rug-extension-spring-boot-project.md'
      - Xml: 'rug/reference/extensions/rug-extension-xml.md'
      - Yml: 'rug/reference/extensions/rug-extension-yml.md'
